# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user_name',
        ),
    ]
